### ISSUE TITLE
Execute Jenkins to report an error

### ISSUE THREAD

**Issue by hanxinhao000** [MasterDevX/Termux-Java#27]
2020-07-30 03:59:17.641+0000 [id=1]	INFO	org.eclipse.jetty.util.log.Log#initialized: Logging initialized @1771ms to org.eclipse.jetty.util.log.JavaUtilLog
2020-07-30 03:59:18.496+0000 [id=1]	INFO	winstone.Logger#logInternal: Beginning extraction from war file
2020-07-30 03:59:29.746+0000 [id=1]	WARNING	o.e.j.s.handler.ContextHandler#setContextPath: Empty contextPath
2020-07-30 03:59:30.247+0000 [id=1]	INFO	org.eclipse.jetty.server.Server#doStart: jetty-9.4.27.v20200227; built: 2020-02-27T18:37:21.340Z; git: a304fd9f351f337e7c0e2a7c28878dd536149c6c; jvm 1.8.0_152-b16
2020-07-30 03:59:34.197+0000 [id=1]	INFO	o.e.j.w.StandardDescriptorProcessor#visitServlet: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2020-07-30 03:59:34.531+0000 [id=1]	INFO	o.e.j.s.s.DefaultSessionIdManager#doStart: DefaultSessionIdManager workerName=node0
2020-07-30 03:59:34.532+0000 [id=1]	INFO	o.e.j.s.s.DefaultSessionIdManager#doStart: No SessionScavenger set, using defaults
2020-07-30 03:59:34.546+0000 [id=1]	INFO	o.e.j.server.session.HouseKeeper#startScavenging: node0 Scavenging every 660000ms
2020-07-30 03:59:37.492+0000 [id=1]	INFO	hudson.WebAppMain#contextInitialized: Jenkins home directory: /home/?/.jenkins found at: $user.home/.jenkins
2020-07-30 03:59:37.786+0000 [id=1]	SEVERE	hudson.util.BootFailure#publish: Failed to initialize Jenkins
java.lang.UnsatisfiedLinkError: /usr/share/jdk8/jre/lib/aarch64/libfontmanager.so: libgcc_s.so.1: cannot open shared object file: No such file or directory (Possible cause: architecture word width mismatch)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1845)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at sun.font.FontManagerNativeLibrary$1.run(FontManagerNativeLibrary.java:61)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.FontManagerNativeLibrary.<clinit>(FontManagerNativeLibrary.java:32)
	at sun.font.SunFontManager$1.run(SunFontManager.java:339)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.SunFontManager.<clinit>(SunFontManager.java:335)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:82)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
	at java.awt.Font.getFont2D(Font.java:491)
	at java.awt.Font.getFamily(Font.java:1220)
	at java.awt.Font.getFamily_NoClientCode(Font.java:1194)
	at java.awt.Font.getFamily(Font.java:1186)
	at java.awt.Font.toString(Font.java:1683)
	at hudson.util.ChartUtil.<clinit>(ChartUtil.java:260)
	at hudson.WebAppMain.contextInitialized(WebAppMain.java:218)
Caused: hudson.util.AWTProblem
	at hudson.WebAppMain.contextInitialized(WebAppMain.java:219)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:933)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:553)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:892)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:356)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1445)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1409)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:825)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:275)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:524)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:407)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:371)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at winstone.Launcher.<init>(Launcher.java:182)
	at winstone.Launcher.main(Launcher.java:355)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at Main._main(Main.java:375)
	at Main.main(Main.java:151)
2020-07-30 03:59:40.574+0000 [id=1]	INFO	o.e.j.s.handler.ContextHandler#doStart: Started w.@29d37757{Jenkins v2.235.2,/,file:///home/%3F/.jenkins/war/,AVAILABLE}{/home/?/.jenkins/war}
2020-07-30 03:59:40.688+0000 [id=1]	INFO	o.e.j.server.AbstractConnector#doStart: Started ServerConnector@4d14b6c2{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2020-07-30 03:59:40.691+0000 [id=1]	INFO	org.eclipse.jetty.server.Server#doStart: Started @24821ms
2020-07-30 03:59:40.693+0000 [id=18]	INFO	winstone.Logger#logInternal: Winstone Servlet Engine running: controlPort=disabled

**Comment by hanxinhao000** [comment]
/usr/share/jdk8/jre/lib/aarch64/libfontmanager.so: libgcc_s.so.1: cannot open shared object file: No such file or directory (Possible cause: architecture word width mismatch)
